* Simple GUI example
** The purpose of this repository
   This repository contains an example of a simple GUI with
   - one frame
   - menu bar with one item to quit the program
   - label with current time
   - label with boolean state of the application program
   - button
   - progress bar counting to 30 seconds repetitively.

   This example serves three purposes:
   1. To show a clean separation of the application from the user
      interface (as in Model-View-Controller). Start by taking a look
      at =main.py= and =Application.py=, especially how simple they
      are.
   2. To demonstrate how a timer can be used to run methods without
      user invocation. See class =Application=.

** Installing and runnin application in VS code
   To install and run the application in VS code, do the following:
   1. Clone the repository.
   2. Create a new =venv=.
      1. In the list of dependencies to install, select =requirements.txt=.
   3. Open =main.py=.
   4. Run Python file.
** License
   Copyright (C) 2021-2025 Jarmo Hurri

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
